FROM python:3.11-slim

# Set basic environment variables
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "servicetitan_inbox_st_to_json.py"]

